######################################################################
# Automatically generated by qmake (3.1) Wed Jan 22 11:02:00 2025
######################################################################

TEMPLATE = app
TARGET = contact
INCLUDEPATH += .

# Directories
QT += widgets
SOURCES += main.cpp FenetrePrincipale.cpp ContactDialog.cpp
HEADERS += FenetrePrincipale.h ContactDialog.h