######################################################################
# Automatically generated by qmake (3.1) Wed Jan 22 11:02:00 2025
######################################################################

TEMPLATE = app
TARGET = debuts
INCLUDEPATH += .

# Directories
QT += widgets
SOURCES += main.cpp MyWindow.cpp MyDialog.cpp
HEADERS += MyWindow.h MyDialog.h